services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: apache_server
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html 
    networks:
      - red1

  db:
    image: mysql
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: clave
    ports:
      - "3306:3306" 
    volumes:
      - ./script/:/docker-entrypoint-initdb.d
      - ./datos_bd:/var/lib/mysql
    networks:
      - red1

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_server
    ports:
      - "8080:443" 
    volumes:
      - ./api:/var/www/html
    networks:
      - red1

volumes:
  datos_bd:

networks:
  red1: